name: MysterriaVoting
version: '1.0.0'
main: net.mysterria.voting.MysterriaVoting
api-version: '1.21'
commands:
  vote:
    usage: /<command>
    permission: voting.vote
  voting:
    usage: /<command> [send|reload]
permissions:
  voting.vote:
    default: true
  voting.send:
    default: op
  voting.reload:
    default: op